version: '3.8'

services:
  clickhouse:
    container_name: clickhouse
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    ports:
      - 19000:9000
      - 18123:8123
      - 19010:19010
      - 19104:9100
    environment:
      CLICKHOUSE_INTERSERVER_HTTP_PORT: 19010
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./config.d:/etc/clickhouse-server/config.d
      - ./user.d:/etc/clickhouse-server/user.d
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    driver: bridge