version: '3.8'

# Single node clickhouse
services:
  ch-node:
    container_name: clickhouse
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    ports:
      - ${CLICKHOUSE_TCP_PORT}:9000
      - ${CLICKHOUSE_HTTP_PORT}:8123
      - ${CLICKHOUSE_INTERSERVER_HTTP_PORT}:${CLICKHOUSE_INTERSERVER_HTTP_PORT}
      - ${PROMETHEUS_EXPORTER_PORT}:9100
    environment:
      PROMETHEUS_EXPORTER_PORT: ${PROMETHEUS_EXPORTER_PORT}
      CLICKHOUSE_INTERSERVER_HTTP_PORT: ${CLICKHOUSE_INTERSERVER_HTTP_PORT}
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./config.d:/etc/clickhouse-server/config.d
      - ./user.d:/etc/clickhouse-server/user.d