#!/bin/bash

export CLICKHOUSE_INTERSERVER_HTTP_PORT=9010
export CLICKHOUSE_TCP_PORT=9000
export PROMETHEUS_EXPORTER_PORT=9105
export CLICKHOUSE_HTTP_PORT=8123
export KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:29092
export CLICKHOUSE_USER=default
export CLICKHOUSE_PASSWORD=''