version: '3.8'

services:
  zookeeper-0:
    image: zookeeper:3.7.0
    container_name: 'zookeeper-0'
    environment:
      - ZOO_AUTOPURGE_PURGEINTERVAL=1
      - ZOO_AUTOPURGE_SNAPRETAINCOUNT=3
      - JVMFLAGS=-Xmx1G -Xms128M
      - ZOO_CFG_EXTRA=clientPort=2181 metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=9101
      - ZOO_LOG4J_PROP=INFO, ROLLINGFILE
    ports:
      - ${ZOOKEPPER_CLIENT_EXTERNAL_PORT}:2181
      - ${PROMETHEUS_JMX_EXTERNAL_PORT}:9101
    volumes:
      - ./logs:/logs