version: "3.0"

services:
  receiver-service:
    image: dachertanov/receiver-service
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      JAVA_OPTS: "-Xmx1G -Xms500m"
      RECEIVER_TOPIC_NAME: "ru.analytical.storage.event"
      RECEIVER_TOPIC_NUM_PARTITIONS: 3
      RECEIVER_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 18080:8080
      - 19100:9100
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    driver: bridge