version: '3.8'

services:
  prometheus:
    image: bitnami/prometheus:2.33.4
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data:/opt/bitnami/prometheus/data
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
    name: common-network