global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zookeeper'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["zookeeper:9105"]

  - job_name: 'kafka'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["kafka:9101"]

  - job_name: 'cassandra'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["cassandra:9103"]

  - job_name: 'kafka-connect'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["kafka-connect:9102"]

  - job_name: 'receiver'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["receiver-service:9100"]

  - job_name: 'clickhouse'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["clickhouse:9104"]