global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zookeeper'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["${ZOOKEEPER_HANDLES}"]

  - job_name: 'kafka'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["${KAFKA_HANDLES}"]

  - job_name: 'cassandra'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["${CASSANDRA_HANDLES}"]

  - job_name: 'kafka-connect'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["${KAFKA_CONNECT_HANDLES}"]

  - job_name: 'receiver'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["${RECEIVER_HANDLES}"]