global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zookeeper'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['212.109.214.181:9101']

  - job_name: 'kafka'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['212.109.214.181:9103']

  - job_name: 'cassandra-node-1'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['212.109.214.181:9102']

  - job_name: 'cassandra-node-2'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['193.8.211.143:9102']

  - job_name: 'cassandra-node-3'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['212.109.214.253:9102']

  - job_name: 'kafka-connect'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['193.8.211.145:9105']

  - job_name: 'http-adapter'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['193.8.211.145:9100']

  - job_name: 'receiver'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['193.8.211.143:9100']