global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'receiver'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.88.129:9100']

  - job_name: 'zookeeper'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.88.129:9101']

  - job_name: 'kafka'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.88.129:9102']

  - job_name: 'clickhouse'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.88.129:9103']

  - job_name: 'cassandra-node-1'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cassandra-node-1:9103']