version: "3.0"

services:
  receiver-service:
    image: dachertanov/receiver-service
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      JAVA_OPTS: "-Xmx1G -Xms500m"
      RECEIVER_TOPIC_NAME: "ru.analytical.storage.event"
      RECEIVER_TOPIC_NUM_PARTITIONS: 3
      RECEIVER_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - ${RECEIVER_REST_API_EXTERNAL_PORT}:8080
      - ${PROMETHEUS_JMX_EXTERNAL_PORT}:9100