{
 "title": "Cassandra",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "212.109.214.181:9102,193.8.211.143:9102,212.109.214.253:9102\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Client_Value{instance=\"$instance\", name=\"connectedNativeClients\",}",
     "legendFormat": "native clients"
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Compaction_Value{instance=\"$instance\", name=\"PendingTasks\"}",
     "legendFormat": "pending compactions"
    },
    {
     "expr": "rate(org_apache_cassandra_metrics_Compaction_Value{instance=\"$instance\", name=\"CompletedTasks\"} [1m])",
     "legendFormat": "compactions per second"
    }
   ]
  },
  {
   "title": "Bytes compacted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(org_apache_cassandra_metrics_Compaction_Count{instance=\"$instance\", name=\"BytesCompacted\"} [1m]) / 1048576",
     "legendFormat": "Mbytes compacted per second"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"} / 1048576",
     "legendFormat": "heap used Mbytes"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{instance=\"$instance\"} / 1048576",
     "legendFormat": "non heap used"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"$instance\"} / 1048576",
     "legendFormat": "heap used"
    }
   ]
  },
  {
   "title": "Opened file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ThreadPools_Value{instance=\"$instance\", name=\"ActiveTasks\"})"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_ThreadPools_Value{instance=\"$instance\", name=\"PendingTasks\"})"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Table_Max{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"WriteLatency\"}"
    },
    {
     "expr": "org_apache_cassandra_metrics_Table_Min{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"WriteLatency\"}"
    },
    {
     "expr": "org_apache_cassandra_metrics_Table_Mean{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"WriteLatency\"}"
    }
   ]
  },
  {
   "title": "SSTable amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Table_Value{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"LiveSSTableCount\",}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Keyspace_Value{instance=\"$instance\", keyspace=\"kion\",name=\"TotalDiskSpaceUsed\",}",
     "legendFormat": "kion"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_Keyspace_Value{instance=\"$instance\", name=\"TotalDiskSpaceUsed\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Table_Max{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"ReadLatency\"}"
    },
    {
     "expr": "org_apache_cassandra_metrics_Table_Min{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"ReadLatency\"}"
    },
    {
     "expr": "org_apache_cassandra_metrics_Table_Mean{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"ReadLatency\"}"
    }
   ]
  },
  {
   "title": "Coordinator read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Table_OneMinuteRate{instance=\"$instance\", keyspace=\"kion\",scope=\"user_event\",name=\"CoordinatorReadLatency\",}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{instance=\"$instance\", }"
    }
   ]
  },
  {
   "title": "Commit log size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_CommitLog_Value{instance=\"$instance\", name=\"TotalCommitLogSize\",} / 1048576",
     "legendFormat": "commit log size mbytes"
    }
   ]
  },
  {
   "title": "Total hints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Storage_Count{instance=\"$instance\", name=\"TotalHints\",}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Table_Value{instance=\"$instance\", keyspace=\"kion\", scope=\"user_event\",name=\"KeyCacheHitRate\",}"
    }
   ]
  }
 ]
}