{
 "title": "Jmeter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Succes/Failure ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(jmeter_success_ratio_success[10s]) / rate(jmeter_success_ratio_total [10s])",
     "legendFormat": "succeses"
    },
    {
     "expr": "rate(jmeter_success_ratio_failure[10s]) / rate(jmeter_success_ratio_total [10s])",
     "legendFormat": "fails"
    }
   ]
  },
  {
   "title": "Response time quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jmeter_response_time_summary", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jmeter_total_requests [10s])",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Response size quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "jmeter_response_size_summary", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Clients [Threads]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "jmeter_threads" }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "jmeter_latency_summary", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}