version: '3.8'

services:
  mongodb:
    restart: always
    container_name: 'mongodb'
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'default'
      MONGO_INITDB_ROOT_PASSWORD: 'default'
      MONGO_INITDB_DATABASE: 'kion'
    ports:
      - 27017:27017

  mongo-express:
      container_name: 'mongo_express'
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: 'default'
        ME_CONFIG_MONGODB_ADMINPASSWORD: 'default'
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_SERVER: 'mongodb'