version: '3.8'

services:

  cassandra-node-1:
    image: cassandra:3.11
    container_name: "cassandra-node-1"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node-1
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=vla
      - CASSANDRA_RACK=no_rack
    volumes:
      - ./cassandra-node-1-data:/var/lib/cassandra
    ports:
      - 9041:9042
    networks:
      - common-network

  cassandra-node-2:
    image: cassandra:3.11
    container_name: "cassandra-node-2"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node-2
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=vla
      - CASSANDRA_RACK=no_rack
    volumes:
      - ./cassandra-node-2-data:/var/lib/cassandra
    ports:
      - 9042:9042
    networks:
      - common-network

  cassandra-node-3:
    image: cassandra:3.11
    container_name: "cassandra-node-3"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node-3
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=vla
      - CASSANDRA_RACK=no_rack
    volumes:
      - ./cassandra-node-3-data:/var/lib/cassandra
    ports:
      - 9043:9042
    networks:
      - common-network

  stargate:
    image: stargateio/stargate-3_11:v1.0.50
    container_name: stargate
    depends_on:
      - cassandra-node-1
    environment:
      - CLUSTER_VERSION=3.11
      - CLUSTER_NAME=cassandra-cluster
      - DATACENTER_NAME=vla
      - RACK_NAME=no_rack
      - SEED=cassandra-node-1
      - ENABLE_AUTH=false
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
    name: common-network