version: '3.8'

services:

  cassandra:
    image: nyusafonov/cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=vla
      - CASSANDRA_RACK=no_rack
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - JVM_OPTS=-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.16.1.jar=9100:/opt/prometheus/prom-jmx-agent-config.yml
    volumes:
      - ./data:/var/lib/cassandra
      - ./prom-jmx-agent-config.yml:/opt/prometheus/prom-jmx-agent-config.yml
    ports:
      - 19042:9042
      - 17000:7000
      - 19103:9100
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    driver: bridge