version: '3.8'

# Following environment variables should be exported:

# CASSANDRA_CLUSTER_NAME
# CASSANDRA_BROADCAST_ADDRESS
# CASSANDRA_SEEDS
# CASSANDRA_ENDPOINT_SNITCH
# CASSANDRA_DC
# CASSANDRA_RACK
# CASSANDRA_EXTERNAL_CLIENT_PORT
# CASSANDRA_EXTERNAL_GOSSIP_PORT
# STARGATE_REST_API_PORT
# STARGATE_AUTH_PORT

services:

  cassandra-node:
    image: cassandra:3.11
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
    volumes:
      - ./data:/var/lib/cassandra
    ports:
      - ${CASSANDRA_EXTERNAL_CLIENT_PORT}:9042
      - ${CASSANDRA_EXTERNAL_GOSSIP_PORT}:7000
    networks:
      - cassandra_network

  stargate:
    image: stargateio/stargate-3_11:v1.0.50
    container_name: stargate
    depends_on:
      - cassandra
    environment:
      - CLUSTER_VERSION=3.11
      - CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - DATACENTER_NAME=${CASSANDRA_DC}
      - RACK_NAME=${CASSANDRA_RACK}
      - SEED=cassandra-node
      - ENABLE_AUTH=false
    ports:
      - ${STARGATE_REST_API_PORT}:8081
      - ${STARGATE_AUTH_PORT}:8082
    networks:
      - cassandra_network

networks:
  cassandra_network:
    name: cassandra-network
    driver: bridge