version: '3.8'

# Following environment variables should be exported:

# CASSANDRA_CLUSTER_NAME
# CASSANDRA_BROADCAST_ADDRESS
# CASSANDRA_SEEDS
# CASSANDRA_ENDPOINT_SNITCH
# CASSANDRA_DC
# CASSANDRA_RACK
# CASSANDRA_EXTERNAL_CLIENT_PORT
# CASSANDRA_EXTERNAL_GOSSIP_PORT
# STARGATE_REST_API_PORT
# STARGATE_AUTH_PORT

services:

  cassandra-node:
    image: nyusafonov/cassandra:latest
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
      - CASSANDRA_LISTEN_ADDRESS=${CASSANDRA_LISTEN_ADDRESS}
      - JVM_OPTS=-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.16.1.jar=9102:/opt/prometheus/prom-jmx-agent-config.yml
    volumes:
      - ./data:/var/lib/cassandra
      - ./prom-jmx-agent-config.yml:/opt/prometheus/prom-jmx-agent-config.yml
    ports:
      - ${CASSANDRA_EXTERNAL_CLIENT_PORT}:9042
      - ${CASSANDRA_EXTERNAL_GOSSIP_PORT}:7000
      - ${PROMETHEUS_EXTERNAL_PORT}:9102
