version: "3.8"

services:

  clickhouse:
    container_name: clickhouse
    image: lunalabsltd/clickhouse-server:21.7.2.7-arm
    ports:
      - 9001:9000
      - 8124:8123
      - 9101:9010
    volumes:
      - type: volume
        source: clickhouse-data
        target: /var/lib/clickhouse
      - type: volume
        source: clickhouse-logs
        target: /var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml

volumes:
  clickhouse-data:
  clickhouse-logs: