version: '3.8'

services:
  kafka:
    image: nyusafonov/kafka:latest
    container_name: 'kafka'
    ports:
      - 19092:9092
      - 9101:9100
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:19092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://kafka:19092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CREATE_TOPICS=ru.analytical.storage.event:3:1
      - EXTRA_ARGS=-javaagent:usr/app/jmx_prometheus_javaagent.jar=9100:/usr/app/prom-jmx-agent-config.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms512M
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
    volumes:
     - ./logs:/opt/kafka/logs
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    driver: bridge