version: '3.8'

services:
  kafka-0:
    image: nyusafonov/kafka:latest
    container_name: 'kafka-0'
    ports:
      - ${KAFKA_CLIENT_EXTERNAL_PORT}:29092
      - ${PROMETHEUS_JMX_EXTERNAL_PORT}:9102
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_HOST}:${KAFKA_ZOOKEEPER_PORT}
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:${KAFKA_CLIENT_EXTERNAL_PORT}
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka-0:9092,OUTSIDE://${MY_PUBLIC_IP}:${KAFKA_CLIENT_EXTERNAL_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CREATE_TOPICS=ru.analytical.storage.event:3:1
      - EXTRA_ARGS=-javaagent:usr/app/jmx_prometheus_javaagent.jar=9102:/usr/app/prom-jmx-agent-config.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms512M
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
    volumes:
     - ./logs:/opt/kafka/logs